=== maharshi6864/c_college_programs/Sem3/XML/practice_exersice/q-2.dtd
<!ELEMENT employee (employee_name,personal_info,salary,designation)>

<!ELEMENT employee_name (#PCDATA)>

<!ELEMENT personal_info (address,birthdate,gender,mobile_no)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT birthdate (#PCDATA)>
<!ELEMENT gender (male|female)>
<!ELEMENT male (#PCDATA)>
<!ELEMENT female (#PCDATA)>
<!ELEMENT mobile_no (#PCDATA)>

<!ELEMENT salary (net_salary,gross_salary,HRA,DA)>
<!ELEMENT net_salary (#PCDATA)>
<!ELEMENT gross_salary (#PCDATA)>
<!ELEMENT HRA (#PCDATA)>
<!ELEMENT DA (#PCDATA)>

<!ELEMENT designation (#PCDATA)>
<!ATTLIST designation post (Manager|Technical|Consultant|Executive|HR) #REQUIRED>

=== maharshi6864/c_college_programs/Sem3/XMl/practice_exersice/q-2.xml
<?xml version="1.0"?>
	
	<!DOCTYPE employee SYSTEM "q-2.dtd">
	
	<employee>
		<employee_name></employee_name>
		<personal_info>
			<address></address>
			<birthdate></birthdate>
			<gender>
				<male></male>
			</gender>
			<mobile_no></mobile_no>
		</personal_info>
		<salary>
			<net_salary></net_salary>
			<gross_salary></gross_salary>
			<HRA></HRA>
			<DA></DA>
		</salary>
		<designation post="Manager"></designation>
	</employee>
