=== maharshi6864/c_college_programs/Sem3/XML/assignment_2/q-1.dtd
<!ELEMENT student (roll_no,name,address,mobile,dob,age,qualification)>
<!ELEMENT roll_no (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT qualification (#PCDATA)>

=== maharshi6864/c_college_programs/Sem3/XML/assignment_2/q-1.xml
<?xml version="1.0"?>
	
<!DOCTYPE student SYSTEM "q-1.dtd">

<student>
	<roll_no>69</roll_no>
	<name>maharshi patel</name>
	<address>navrangpura</address>
	<mobile>635126412789812</mobile>
	<dob>13/09/2004</dob>
	<age>19</age>
	<qualification></qualification>
</student>
