=== maharshi6864/c_college_programs/Sem3/XML/assignment_2/q-4.dtd
<!ELEMENT student (student_name,personal_info,result)>
<!ELEMENT student_name (#PCDATA)>
<!ELEMENT personal_info (address,birthdate,gender,mobile_no,address)>
<!ELEMENT result (total,percentage,grade)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT birthdate (#PCDATA)>
<!ELEMENT gender (male|female)>
<!ELEMENT female (#PCDATA)>
<!ELEMENT male (#PCDATA)>
<!ELEMENT mobile_no (#PCDATA)>
<!ELEMENT total (#PCDATA)>
<!ELEMENT percentage (#PCDATA)>
<!ELEMENT grade (Pass|First|Dist|Second|Fail)>
<!ELEMENT Pass (#PCDATA)>
<!ELEMENT First (#PCDATA)>
<!ELEMENT Dist (#PCDATA)>
<!ELEMENT Second (#PCDATA)>
<!ELEMENT Fail (#PCDATA)>

=== maharshi6864/c_college_programs/Sem3/XML/assignment_2/q-4.xml
<?xml version="1.0" ?>
	<!DOCTYPE student SYSTEM "q-4.dtd">
	<student>
		<student_name>
		</student_name>
		<personal_info>
			<address></address>
			<birthdate></birthdate>
			<gender><male></male></gender>
			<mobile_no></mobile_no>
			<address></address>
		</personal_info>
		<result>
			<total></total>
			<percentage></percentage>
			<grade>
				<Pass></Pass>
			</grade>
		</result>
	</student>
