=== maharshi6864/c_college_programs/Sem3/XML/assignment_2/q-6.dtd
<!ELEMENT student (name,id,plan)>
<!ELEMENT name (fname,lname)>
<!ELEMENT fname (#PCDATA)>
<!ELEMENT lname (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT plan ((course)*)>
<!ELEMENT course (coursename,shortname,(record)*)>
<!ELEMENT coursename (#PCDATA)>
<!ELEMENT shortname (#PCDATA)>
<!ELEMENT record (grade,date)>
<!ELEMENT grade (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ATTLIST course year CDATA #REQUIRED>

=== maharshi6864/c_college_programs/Sem3/XMl/assignment_2/q-6.xml
<?xml version="1.0" ?>
	<!DOCTYPE student SYSTEM "q-6.dtd" >
	<student>
		<name>
			<fname>maharshi</fname>
			<lname>patel</lname>
		</name>
		<id>69</id>
		<plan>
			<course year="2023">
				<coursename>Intergreted Masters in Science Of INformation Technology</coursename>
				<shortname>iMscIT</shortname>
				<record >
					<grade>O+</grade>
					<date>20/07/2024</date>
				</record>
			</course>
		</plan>
	</student>
