=== maharshi6864/c_college_programs/Sem3/XMl/assignment_2/q-7.dtd
<!ELEMENT email (from,to,content,course)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT content (person,exercises)>
<!ELEMENT person (#PCDATA)>
<!ELEMENT exercises (exercise)>
<!ELEMENT exercise (topic,description)>
<!ELEMENT topic (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT course (#PCDATA)>

=== maharshi6864/c_college_programs/Sem3/XMl/assignment_2/q-7.xml
<?xml version="1.0" ?>
	<!DOCTYPE email SYSTEM "q-7.dtd">
	<email>
		<from></from>
		<to></to>
		<content>
			<person></person>
			<exercises>
				<exercise>
					<topic></topic>
					<description></description>
				</exercise>
			</exercises>
		</content>
		<course>
			iMscIT
		</course>
	</email>
