=== maharshi6864/c_college_programs/Sem3/XMl/assignment_2/q-8.dtd
<!ELEMENT student (roll_no,name,marks,rank)>
<!ELEMENT roll_no (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT marks (web_technologies,xml,J2EE,NS)>
<!ELEMENT web_technologies (#PCDATA)>
<!ELEMENT J2EE (#PCDATA)>
<!ELEMENT xml (#PCDATA)>
<!ELEMENT NS (#PCDATA)>
<!ELEMENT rank (#PCDATA)>

=== maharshi6864/c_college_programs/Sem3/XMl/assignment_2/q-8.xml
<?xml version="1.0"?>
	<!DOCTYPE student SYSTEM "q-8.dtd">
	<student>
		<roll_no></roll_no>
		<name></name>
		<marks>
				<web_technologies></web_technologies>
				<xml></xml>
				<J2EE></J2EE>
				<NS></NS>
		</marks>
		<rank></rank>
	</student>
